### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by stevepurkiss** [eyss/h-wiki-front#6]
Thank you for your work! Keen to try this out, followed all the instructions but get this on `npm start`:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/Users/steve/Holoplay/h-wiki-front/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/index.js:317:13)
    at /Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/Users/steve/Holoplay/h-wiki-front/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/index.js:317:13)
    at /Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/Users/steve/Holoplay/h-wiki-front/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/Users/steve/Holoplay/h-wiki-front/node_modules/express/lib/router/layer.js:95:5)
```
Tried changing config from memory to file as per instructions as that's the only place I've seen a reference to any path variable just in case that was the issue but made no difference.

**Comment by hector0513** [comment]
maybe the problem is the version of npm, you can delete node_modules and run yarn and yarn start

**Comment by stevepurkiss** [comment]
@hector0513 ooo thanks for the pointers, got it working!

I'd installed npm using brew but seems I'd installed yarn not using brew and hadn't linked them, no idea really I'm from back-end but had tried out the new Drupal theme a few months back so had to set up yarn.
